services:
  freshrss:
    image: freshrss/freshrss:latest
    environment:
      - SERVICE_FQDN_FRESHRSS_80
      - CRON_MIN=${CRON_MIN:-1,31}
      - MARIADB_DB=${MARIADB_DATABASE:-freshrss}
      - MARIADB_USER=${SERVICE_USER_MARIADB}
      - MARIADB_PASSWORD=${SERVICE_PASSWORD_MARIADB}
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    depends_on:
      freshrss-db:  
  freshrss-db:
    image: mariadb:11
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=${MARIADB_DATABASE:-freshrss}
      - MYSQL_USER=${SERVICE_USER_MARIADB}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MARIADB}
